-- Atomic, server-only quota reservations for paid LiveAvatar session creation.

create table if not exists public.api_rate_limit_events (
  id bigint generated by default as identity primary key,
  event_type text not null,
  key_hash text not null,
  created_at timestamptz not null default now()
);

create index if not exists idx_api_rate_limit_events_lookup
  on public.api_rate_limit_events (event_type, key_hash, created_at desc);
create index if not exists idx_api_rate_limit_events_global
  on public.api_rate_limit_events (event_type, created_at desc);

alter table public.api_rate_limit_events enable row level security;

create or replace function public.reserve_api_rate_limit(
  p_event_type text,
  p_key_hash text,
  p_per_minute integer,
  p_per_day integer,
  p_global_per_day integer
)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
  minute_count integer;
  day_count integer;
  global_day_count integer;
begin
  if p_event_type is null or p_event_type = ''
    or p_key_hash is null or p_key_hash = ''
    or p_per_minute < 1 or p_per_day < 1 or p_global_per_day < 1 then
    return false;
  end if;

  -- Lock globally first, then per visitor, so every reservation observes and
  -- updates one consistent cost ceiling even under concurrent requests.
  perform pg_advisory_xact_lock(hashtextextended('ww-rate-limit:' || p_event_type || ':global', 0));
  perform pg_advisory_xact_lock(hashtextextended('ww-rate-limit:' || p_event_type || ':' || p_key_hash, 0));

  delete from public.api_rate_limit_events
    where created_at < now() - interval '2 days';

  select count(*) into minute_count
    from public.api_rate_limit_events
    where event_type = p_event_type
      and key_hash = p_key_hash
      and created_at >= now() - interval '1 minute';

  select count(*) into day_count
    from public.api_rate_limit_events
    where event_type = p_event_type
      and key_hash = p_key_hash
      and created_at >= now() - interval '1 day';

  select count(*) into global_day_count
    from public.api_rate_limit_events
    where event_type = p_event_type
      and created_at >= now() - interval '1 day';

  if minute_count >= p_per_minute
    or day_count >= p_per_day
    or global_day_count >= p_global_per_day then
    return false;
  end if;

  insert into public.api_rate_limit_events (event_type, key_hash)
    values (p_event_type, p_key_hash);
  return true;
end;
$$;

revoke all on function public.reserve_api_rate_limit(text, text, integer, integer, integer) from public;
revoke all on function public.reserve_api_rate_limit(text, text, integer, integer, integer) from anon;
revoke all on function public.reserve_api_rate_limit(text, text, integer, integer, integer) from authenticated;
grant execute on function public.reserve_api_rate_limit(text, text, integer, integer, integer) to service_role;
